### ISSUE TITLE
Crash when waking computer from sleep

### ISSUE THREAD

**Issue by Riff-Skippelton** [Aurora-RGB/Aurora#122]
Has happened consistently since last update.

![image](https://user-images.githubusercontent.com/81395984/213597306-0c3a624b-f803-4f7d-a5d5-91c7855b059a.png)

**Comment by Rukario** [comment]
Exactly same problem!

**Comment by Aytackydln** [comment]
Should be fixed:
https://github.com/Aurora-RGB/Aurora/releases/tag/v115

**Comment by Rukario** [comment]
How do you dictate it's fixed? It wasn't fixed for me unfortunately. Windows is set to go to sleep from power button, with no hibernation. Tested on Windows 11 on Intel i7-7700K and Intel i9-11900K, Ducky One 2 TKL board.

**Comment by Rukario** [comment]
Also I'm not sure which version it broke on, but it used to work fine after wake not so long ago. Are you able to replicate the problem yourself so you can be sure it's fixed?

**Comment by Aytackydln** [comment]
Before the fix, by clicking "Sleep" from windows menu I got the same error as you showed. I didn't get the error after the fix.

I didn't hear from you after release so I assumed it was fixed. Are you still getting the same error?

**Comment by Rukario** [comment]
Yeah, sorry I should've replied in time, it's still a problem for me. Please try another computer, I think the number of samples is too low for you to confirm it's fixed for everyone or not. A restart delay function in the code looks like a mere bandaid fix, you can do better...

**Comment by Aytackydln** [comment]
Well, codes were copied from another part of Aurora. Error happens while computer is goin to sleep, not while waking. 
Probably there is a race condition that windows sometimes (for you, always) disables sound devices before sending sleep event to Aurora

**Comment by Aytackydln** [comment]
Can you verify it is fixed here:
https://github.com/Aurora-RGB/Aurora/releases/tag/v116

**Comment by Rukario** [comment]
Unfortunately it didn't

**Comment by Aytackydln** [comment]
can you upload the full logs after the crash? You can find the location in settings of aurora

**Comment by Rukario** [comment]
[2023-01-28 10.35.44.log](https://github.com/Aurora-RGB/Aurora/files/10527994/2023-01-28.10.35.44.log)

**Comment by Riff-Skippelton** [comment]
[INFO] 08:39:57: 
========================================
Operation System: Windows 10 Education
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 10.0.19045.0
System Directory: C:\WINDOWS\system32
Executing Directory: C:\Program Files\Aurora
Launch Directory: C:\Program Files\Aurora
Processor Count: 12
SystemPageSize: 4096
Environment Version: 6.0.13
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: v115
========================================
 
[INFO] 08:39:57: Loading devices from assembly... 
[INFO] 08:39:58: Loading Configuration 
[INFO] 08:39:58: Loading Input Hooking 
[INFO] 08:39:58: Loaded Input Hooking 
[INFO] 08:39:58: Fetching latest pointers 
[INFO] 08:39:58: Loading Plugins 
[INFO] 08:39:58: Loaded Plugins 
[INFO] 08:39:58: Starting IpcListener 
[INFO] 08:39:58: [IPCServer] Pipe created -1 
[INFO] 08:39:58: Listening for wrapper integration calls... 
[INFO] 08:39:58: Loading Applications 
[INFO] 08:40:01: NVAPI 
[INFO] 08:40:01: Version: NVidia Complete Version 1.10 
[INFO] 08:40:01: Number of GPUs: 1 
[INFO] 08:40:01: AMD Display Library 
[INFO] 08:40:01: Status: -1 
[INFO] 08:40:03: Started regular ambilight mode 
[INFO] 08:40:03: Loading RazerSdkManager 
[INFO] 08:40:03: RazerSdkManager loaded successfully! 
[INFO] 08:40:03: Loading KB Layouts 
[INFO] 08:40:03: Loaded KB Layouts 
[INFO] 08:40:03: Loading ResourceDictionaries... 
[INFO] 08:40:03: Loaded ResourceDictionaries 
[WARN] 08:40:04: Could not find an AutoNode getter method for field '_ParsedData' of type 'JObject'. It will not be automatically populated. 
[INFO] 08:40:05: Loading Device Manager 
[INFO] 08:40:05: [Device][Logitech] Trying to initialize Logitech using the dll for GHUB 
[INFO] 08:40:05: Loading ConfigUI... 
[INFO] 08:40:05: [Device][LightFX] Initialized Successfully. 
[INFO] 08:40:05: [Device][Corsair] Initialized Successfully. 
[ERROR] 08:40:05: SteelSeries GameSense SDK could not be initialized: System.IO.FileNotFoundException: Core Props file could not be found at "C:\ProgramData/SteelSeries/SteelSeries Engine 3/coreProps.json"
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\GameSenseSDK.cs:line 58
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize() in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\SteelSeriesDevice.cs:line 49 
[INFO] 08:40:05: [Device][SteelSeries] Initialized Successfully. 
[INFO] 08:40:05: [Device][Bloody (RGB.NET)] Initialized Successfully. 
[INFO] 08:40:05: [Device][Sony DualShock 4(PS4)] Initialized Successfully. 
[INFO] 08:40:05: [Device][Logitech] Initialized Successfully. 
[INFO] 08:40:05: [Device][CoolerMaster (RGB.NET)] Initialized Successfully. 
[INFO] 08:40:10: [Device][OpenRGB] Initialized Successfully. 
[DEBUG] 09:47:22: RazerManager current app:  [0] 
[DEBUG] 13:03:53: RazerManager current app:  [0] 
[INFO] 13:19:30: Show Window called 
[DEBUG] 13:35:05: RazerManager current app:  [0] 
[DEBUG] 21:28:19: RazerManager current app:  [0] 
[ERROR] 21:28:23: Exception in GetActiveWindowsProcessTitle System.ComponentModel.Win32Exception (5): Access is denied.
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModules(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModule(Int32 processId)
   at Aurora.Modules.ProcessMonitor.ActiveProcessMonitor.GetActiveWindowsProcessName() in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Modules\ProcessMonitor\ActiveProcessMonitor.cs:line 198
[DEBUG] 21:43:32: RazerManager current app:  [0] 
[DEBUG] 22:45:55: RazerManager current app:  [0] 
[WARN] 23:02:29: Could not find an AutoNode getter method for field '_ParsedData' of type 'JObject'. It will not be automatically populated. 
[INFO] 23:40:38: Suspending Devices 
[INFO] 23:40:38: [Device][Bloody (RGB.NET)] Shutdown 
[INFO] 23:40:38: [Device][CoolerMaster (RGB.NET)] Shutdown 
[INFO] 23:40:38: [Device][Corsair] Shutdown 
[INFO] 23:40:38: [Device][Logitech] Shutdown 
[INFO] 08:03:50: [Device][Sony DualShock 4(PS4)] Detected device list changed, rescanning for controllers... 
[INFO] 08:03:59: Resuming Devices -- PowerModes.Resume 
[INFO] 08:04:01: [Device][Logitech] Trying to initialize Logitech using the dll for GHUB 
[INFO] 08:04:01: [Device][LightFX] Initialized Successfully. 
[INFO] 08:04:01: [Device][CoolerMaster (RGB.NET)] Initialized Successfully. 
[INFO] 08:04:01: [Device][Corsair] Initialized Successfully. 
[INFO] 08:04:01: [Device][Bloody (RGB.NET)] Initialized Successfully. 
[ERROR] 08:04:01: SteelSeries GameSense SDK could not be initialized: System.IO.FileNotFoundException: Core Props file could not be found at "C:\ProgramData/SteelSeries/SteelSeries Engine 3/coreProps.json"
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\GameSenseSDK.cs:line 58
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize() in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\SteelSeriesDevice.cs:line 49 
[INFO] 08:04:01: [Device][SteelSeries] Initialized Successfully. 
[INFO] 08:04:01: [Device][Sony DualShock 4(PS4)] Initialized Successfully. 
[INFO] 08:04:01: [Device][Logitech] Initialized Successfully. 
[FATAL] 08:04:05: Fatal Exception caught : System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Runtime.InteropServices.COMException (0x80070490): Element not found. (0x80070490)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at NAudio.CoreAudioApi.MMDeviceEnumerator.GetDefaultAudioEndpoint(DataFlow dataFlow, Role role)
   at Aurora.Modules.AudioCapture.AudioDeviceProxy.UpdateDevice() in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Modules\AudioCapture\AudioDeviceProxy.cs:line 96
   at Aurora.Modules.AudioCapture.AudioDeviceProxy.SystemEvents_PowerModeChanged(Object sender, PowerModeChangedEventArgs e) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Modules\AudioCapture\AudioDeviceProxy.cs:line 226
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Microsoft.Win32.SystemEvents.SystemEventInvokeInfo.InvokeCallback(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Runtime.InteropServices.COMException (0x80070490): Element not found. (0x80070490)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at NAudio.CoreAudioApi.MMDeviceEnumerator.GetDefaultAudioEndpoint(DataFlow dataFlow, Role role)
   at Aurora.Modules.AudioCapture.AudioDeviceProxy.UpdateDevice() in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Modules\AudioCapture\AudioDeviceProxy.cs:line 96
   at Aurora.Modules.AudioCapture.AudioDeviceProxy.SystemEvents_PowerModeChanged(Object sender, PowerModeChangedEventArgs e) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Modules\AudioCapture\AudioDeviceProxy.cs:line 226
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Microsoft.Win32.SystemEvents.SystemEventInvokeInfo.InvokeCallback(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[INFO] 08:04:06: [Device][OpenRGB] Initialized Successfully. 
[DEBUG] 08:24:03: RazerManager current app:  [0] 
[INFO] 10:35:35: Show Window called 
[INFO] 10:37:26: [Device][Bloody (RGB.NET)] Shutdown 
[INFO] 10:37:26: [Device][CoolerMaster (RGB.NET)] Shutdown 
[INFO] 10:37:26: [Device][Corsair] Shutdown 
[INFO] 10:37:26: [Device][Logitech] Shutdown 
[WARN] 10:37:26: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at Aurora.Controls.Control_DeviceItem.Update_controls_timer_Elapsed(Object sender, ElapsedEventArgs e) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Controls\Control_DeviceItem.xaml.cs:line 64 

[INFO] 08:39:04: 
========================================
Operation System: Windows 10 Education
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 10.0.19045.0
System Directory: C:\WINDOWS\system32
Executing Directory: C:\Program Files\Aurora
Launch Directory: C:\Program Files\Aurora
Processor Count: 12
SystemPageSize: 4096
Environment Version: 6.0.13
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: v115
========================================
 
[INFO] 08:39:04: Loading devices from assembly... 
[INFO] 08:39:04: Loading Configuration 
[INFO] 08:39:05: Loading Input Hooking 
[INFO] 08:39:05: Loaded Input Hooking 
[INFO] 08:39:05: Fetching latest pointers 
[ERROR] 08:39:07: AudioCapture error System.Runtime.InteropServices.COMException (0x80070490): Element not found. (0x80070490)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at NAudio.CoreAudioApi.MMDeviceEnumerator.GetDefaultAudioEndpoint(DataFlow dataFlow, Role role)
   at Aurora.Modules.AudioCapture.AudioDeviceProxy.UpdateDevice() in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Modules\AudioCapture\AudioDeviceProxy.cs:line 96
   at Aurora.Modules.AudioCapture.AudioDeviceProxy.set_DeviceId(String value) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Modules\AudioCapture\AudioDeviceProxy.cs:line 84
   at Aurora.Modules.AudioCapture.AudioDeviceProxy..ctor(String deviceId, DataFlow flow) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Modules\AudioCapture\AudioDeviceProxy.cs:line 42
   at Aurora.Modules.AudioCaptureModule.InitializeLocalInfoProxies() in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Modules\AudioCaptureModule.cs:line 55
[INFO] 08:39:07: Loading Plugins 
[INFO] 08:39:07: Loaded Plugins 
[INFO] 08:39:07: Starting IpcListener 
[INFO] 08:39:07: [IPCServer] Pipe created -1 
[INFO] 08:39:07: Listening for wrapper integration calls... 
[INFO] 08:39:07: Loading Applications 
[INFO] 08:39:09: NVAPI 
[INFO] 08:39:09: Version: NVidia Complete Version 1.10 
[INFO] 08:39:09: Number of GPUs: 1 
[INFO] 08:39:09: AMD Display Library 
[INFO] 08:39:09: Status: -1 
[FATAL] 08:39:10: Fatal Exception caught : System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Runtime.InteropServices.COMException (0x80070490): Element not found. (0x80070490)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at NAudio.CoreAudioApi.MMDeviceEnumerator.GetDefaultAudioEndpoint(DataFlow dataFlow, Role role)
   at Aurora.Modules.AudioCapture.AudioDeviceProxy.UpdateDevice() in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Modules\AudioCapture\AudioDeviceProxy.cs:line 96
   at Aurora.Modules.AudioCapture.AudioDeviceProxy.set_DeviceId(String value) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Modules\AudioCapture\AudioDeviceProxy.cs:line 84
   at Aurora.Modules.AudioCapture.AudioDeviceProxy..ctor(String deviceId, DataFlow flow) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Modules\AudioCapture\AudioDeviceProxy.cs:line 42
   at Aurora.Modules.AudioCapture.AudioDeviceProxy..ctor(DataFlow flow) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Modules\AudioCapture\AudioDeviceProxy.cs:line 34
   at Aurora.Settings.Layers.EqualizerLayerHandler.get_DeviceProxy() in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Settings\Layers\EqualizerLayerHandler.cs:line 175
   at Aurora.Settings.Layers.EqualizerLayerHandler.PropertiesChanged(Object sender, PropertyChangedEventArgs args) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Settings\Layers\EqualizerLayerHandler.cs:line 432
   at Aurora.Settings.Layers.LayerHandlerProperties`1.OnPropertiesChanged(Object sender) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Settings\Layers\LayerHandler.cs:line 146
   at Aurora.Settings.Layers.LayerHandler`1.set_Properties(TProperty value) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Settings\Layers\LayerHandler.cs:line 239
   at Aurora.Profiles.Osu.OsuProfile.Reset() in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Profiles\Osu\OsuProfile.cs:line 20
   at Aurora.Settings.ApplicationProfile..ctor() in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Settings\ApplicationProfile.cs:line 40
   at Aurora.Profiles.Osu.OsuProfile..ctor() in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Profiles\Osu\OsuProfile.cs:line 13
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   --- End of inner exception stack trace ---
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at Aurora.Profiles.Application.CreateNewProfile(String profileName) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Profiles\Application.cs:line 173
   at Aurora.Profiles.Application.AddNewProfile(String profileName) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Profiles\Application.cs:line 194
   at Aurora.Profiles.Application.LoadProfiles() in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Profiles\Application.cs:line 617
   at Aurora.Profiles.Application.Initialize() in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Profiles\Application.cs:line 132
   at Aurora.Profiles.LightingStateManager.Initialize() in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Profiles\LightingStateManager.cs:line 113
   at Aurora.Modules.LightningStateManagerModule.Initialize() in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Modules\LightningStateManagerModule.cs:line 28
   at Aurora.Modules.LightningStateManagerModule.InitializeAsync() in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Lombok.NET\Lombok.NET.MethodGenerators.AsyncGenerator\Aurora_Modules_LightningStateManagerModule.Initialize.g.cs:line 12
   at Aurora.App.<>c.<OnStartup>b__15_1(IAuroraModule m) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\App.xaml.cs:line 108
   at System.Collections.Generic.List`1.ConvertAll[TOutput](Converter`2 converter)
   at Aurora.App.OnStartup(StartupEventArgs e) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\App.xaml.cs:line 108
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Runtime.InteropServices.COMException (0x80070490): Element not found. (0x80070490)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at NAudio.CoreAudioApi.MMDeviceEnumerator.GetDefaultAudioEndpoint(DataFlow dataFlow, Role role)
   at Aurora.Modules.AudioCapture.AudioDeviceProxy.UpdateDevice() in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Modules\AudioCapture\AudioDeviceProxy.cs:line 96
   at Aurora.Modules.AudioCapture.AudioDeviceProxy.set_DeviceId(String value) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Modules\AudioCapture\AudioDeviceProxy.cs:line 84
   at Aurora.Modules.AudioCapture.AudioDeviceProxy..ctor(String deviceId, DataFlow flow) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Modules\AudioCapture\AudioDeviceProxy.cs:line 42
   at Aurora.Modules.AudioCapture.AudioDeviceProxy..ctor(DataFlow flow) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Modules\AudioCapture\AudioDeviceProxy.cs:line 34
   at Aurora.Settings.Layers.EqualizerLayerHandler.get_DeviceProxy() in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Settings\Layers\EqualizerLayerHandler.cs:line 175
   at Aurora.Settings.Layers.EqualizerLayerHandler.PropertiesChanged(Object sender, PropertyChangedEventArgs args) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Settings\Layers\EqualizerLayerHandler.cs:line 432
   at Aurora.Settings.Layers.LayerHandlerProperties`1.OnPropertiesChanged(Object sender) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Settings\Layers\LayerHandler.cs:line 146
   at Aurora.Settings.Layers.LayerHandler`1.set_Properties(TProperty value) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Settings\Layers\LayerHandler.cs:line 239
   at Aurora.Profiles.Osu.OsuProfile.Reset() in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Profiles\Osu\OsuProfile.cs:line 20
   at Aurora.Settings.ApplicationProfile..ctor() in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Settings\ApplicationProfile.cs:line 40
   at Aurora.Profiles.Osu.OsuProfile..ctor() in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Profiles\Osu\OsuProfile.cs:line 13
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   --- End of inner exception stack trace ---
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at Aurora.Profiles.Application.CreateNewProfile(String profileName) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Profiles\Application.cs:line 173
   at Aurora.Profiles.Application.AddNewProfile(String profileName) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Profiles\Application.cs:line 194
   at Aurora.Profiles.Application.LoadProfiles() in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Profiles\Application.cs:line 617
   at Aurora.Profiles.Application.Initialize() in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Profiles\Application.cs:line 132
   at Aurora.Profiles.LightingStateManager.Initialize() in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Profiles\LightingStateManager.cs:line 113
   at Aurora.Modules.LightningStateManagerModule.Initialize() in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Modules\LightningStateManagerModule.cs:line 28
   at Aurora.Modules.LightningStateManagerModule.InitializeAsync() in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Lombok.NET\Lombok.NET.MethodGenerators.AsyncGenerator\Aurora_Modules_LightningStateManagerModule.Initialize.g.cs:line 12
   at Aurora.App.<>c.<OnStartup>b__15_1(IAuroraModule m) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\App.xaml.cs:line 108
   at System.Collections.Generic.List`1.ConvertAll[TOutput](Converter`2 converter)
   at Aurora.App.OnStartup(StartupEventArgs e) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\App.xaml.cs:line 108
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[FATAL] 08:39:53: Fatal Exception caught : System.NullReferenceException: Object reference not set to an instance of an object.
   at Aurora.Profiles.LightingStateManager.Dispose() in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Profiles\LightingStateManager.cs:line 635
   at Aurora.Modules.LightningStateManagerModule.Dispose() in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Modules\LightningStateManagerModule.cs:line 44
   at Aurora.Modules.LightningStateManagerModule.DisposeAsync() in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Lombok.NET\Lombok.NET.MethodGenerators.AsyncGenerator\Aurora_Modules_LightningStateManagerModule.Dispose.g.cs:line 12
   at Aurora.App.<>c.<OnExit>b__19_0(IAuroraModule m) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\App.xaml.cs:line 265
   at System.Collections.Generic.List`1.ConvertAll[TOutput](Converter`2 converter)
   at Aurora.App.OnExit(ExitEventArgs e) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\App.xaml.cs:line 265
   at System.Windows.Application.DoShutdown()
   at System.Windows.Application.ShutdownImpl()
   at System.Windows.Application.ShutdownCallback(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) System.NullReferenceException: Object reference not set to an instance of an object.
   at Aurora.Profiles.LightingStateManager.Dispose() in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Profiles\LightingStateManager.cs:line 635
   at Aurora.Modules.LightningStateManagerModule.Dispose() in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Modules\LightningStateManagerModule.cs:line 44
   at Aurora.Modules.LightningStateManagerModule.DisposeAsync() in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\Lombok.NET\Lombok.NET.MethodGenerators.AsyncGenerator\Aurora_Modules_LightningStateManagerModule.Dispose.g.cs:line 12
   at Aurora.App.<>c.<OnExit>b__19_0(IAuroraModule m) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\App.xaml.cs:line 265
   at System.Collections.Generic.List`1.ConvertAll[TOutput](Converter`2 converter)
   at Aurora.App.OnExit(ExitEventArgs e) in D:\a\Aurora\Aurora\Project-Aurora\Project-Aurora\App.xaml.cs:line 265
   at System.Windows.Application.DoShutdown()
   at System.Windows.Application.ShutdownImpl()
   at System.Windows.Application.ShutdownCallback(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Aytackydln** [comment]
please include logs as a file. It hinders readability of whole thread

**Comment by Aytackydln** [comment]
How is it on last version?
https://github.com/Aurora-RGB/Aurora/releases/tag/v117

**Comment by Rukario** [comment]
Still a problem in v117, Here's a log
[2023-01-29 12.31.21.log](https://github.com/Aurora-RGB/Aurora/files/10530784/2023-01-29.12.31.21.log)

I've noticed a few extra information in the v116 log that may help you
[2023-01-29 02.34.52.log](https://github.com/Aurora-RGB/Aurora/files/10530787/2023-01-29.02.34.52.log)

**Comment by Aytackydln** [comment]
can you try latest version now
https://github.com/Aurora-RGB/Aurora/releases/tag/v122

**Comment by Rukario** [comment]
Still broken

Here's today's logs

[2023-02-12 09.26.02.log](https://github.com/Aurora-RGB/Aurora/files/10716912/2023-02-12.09.26.02.log)
[2023-02-12 09.26.49.log](https://github.com/Aurora-RGB/Aurora/files/10716913/2023-02-12.09.26.49.log)
[2023-02-12 09.33.28.log](https://github.com/Aurora-RGB/Aurora/files/10716914/2023-02-12.09.33.28.log)
[2023-02-12 09.37.00.log](https://github.com/Aurora-RGB/Aurora/files/10716915/2023-02-12.09.37.00.log)
[2023-02-12 09.39.31.log](https://github.com/Aurora-RGB/Aurora/files/10716916/2023-02-12.09.39.31.log)
[2023-02-12 09.45.37.log](https://github.com/Aurora-RGB/Aurora/files/10716917/2023-02-12.09.45.37.log)

Just so you know Aurora actually doesn't crash until I dismiss an error popup. The lighting on keyboard works fine. The word "fatally crash" is what the error popup said.

**Comment by Aytackydln** [comment]
https://github.com/Aurora-RGB/Aurora/releases/tag/v125

**Comment by Rukario** [comment]
Still a problem unfortunately -_-

There's always 3 error popups, 3 error popups every time the PC wakes from sleep.

[2023-02-13 13.46.34.log](https://github.com/Aurora-RGB/Aurora/files/10726630/2023-02-13.13.46.34.log)
[2023-02-13 13.51.21.log](https://github.com/Aurora-RGB/Aurora/files/10726632/2023-02-13.13.51.21.log)
[2023-02-13 13.51.46.log](https://github.com/Aurora-RGB/Aurora/files/10726633/2023-02-13.13.51.46.log)

**Comment by Aytackydln** [comment]
Can you check if it still happens with v131?

**Comment by Rukario** [comment]
Yes, it's still happening with v131. Same usual 3 error popups every wake.

[2023-03-11 16.36.57.log](https://github.com/Aurora-RGB/Aurora/files/10950014/2023-03-11.16.36.57.log)
[2023-03-11 21.02.43.log](https://github.com/Aurora-RGB/Aurora/files/10950015/2023-03-11.21.02.43.log)
[2023-03-11 21.03.59.log](https://github.com/Aurora-RGB/Aurora/files/10950016/2023-03-11.21.03.59.log)

**Comment by Rukario** [comment]
I've decided to bisect the versions to find the earliest version to cause this 3 error popups, it seems v95 is the first problematic version whereas v94 worked fine.

**Comment by Aytackydln** [comment]
can you try this version any give feedback?

https://github.com/Aurora-RGB/Aurora/releases/tag/v135

**Comment by Rukario** [comment]
No more 3x error popups every wake, that's good! But the Aurora closed itself on wake (or when computer goes to sleep) so I've had to relaunch it for every wake.

[2023-04-28 13.28.02.log](https://github.com/Aurora-RGB/Aurora/files/11357148/2023-04-28.13.28.02.log)
[2023-04-28 13.31.08.log](https://github.com/Aurora-RGB/Aurora/files/11357149/2023-04-28.13.31.08.log)
[2023-04-28 13.33.08.log](https://github.com/Aurora-RGB/Aurora/files/11357150/2023-04-28.13.33.08.log)

**Comment by Aytackydln** [comment]
Can you try again with this:

https://github.com/Aurora-RGB/Aurora/releases/tag/v136

**Comment by Rukario** [comment]
Same problem, logs don't look different aside incremental version.

However my another PC still have the same 3 error popups, not sure how it's retained. It missed out the v135

Suspecting if v135 causing the problem, I've tried new Aurora profile for v137 (and new Aurora install), same problem of Aurora closing itself on wake on my main PC, new profile on 2nd PC, same 3 error popups.

main PC has RTX 2060 discrete GPU and Ducky One 2 + Logitech G502 mouse (Aurora run for just Ducky, all other plugins are disabled and no Logitech software installed), DisplayPort 1.4 to my monitor. Windows 11 beta

2nd PC has Logitech software for Logitech G910 keyboard, Intel UHD 730 iGPU using recent Intel software, HDMI 2.0 to my HDTV. Windows 11 release

Maybe because of Logitech software + Aurora run for Logitech G910? I'm not sure, I'll investigate more if you're interested.

**Comment by Rukario** [comment]
So for the log files, perhaps nothing special to see here.

[2023-05-07 13.51.12.log](https://github.com/Aurora-RGB/Aurora/files/11416067/2023-05-07.13.51.12.log)
[2023-05-07 13.53.29.log](https://github.com/Aurora-RGB/Aurora/files/11416068/2023-05-07.13.53.29.log)
[2023-05-07 13.59.21.log](https://github.com/Aurora-RGB/Aurora/files/11416069/2023-05-07.13.59.21.log)

Also it appears that when Aurora was closed on wake there's familiar error message in Windows Event Viewer. It says
`
Application: Aurora.exe
CoreCLR Version: 6.0.1623.17311
.NET Version: 6.0.16
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException (0x88890004): 0x88890004
   at NAudio.CoreAudioApi.Interfaces.IAudioClient.Stop()
   at NAudio.CoreAudioApi.AudioClient.Stop()
   at NAudio.CoreAudioApi.WasapiCapture.CaptureThread(AudioClient client)
   at NAudio.CoreAudioApi.WasapiCapture.<StartRecording>b__35_0()
   at System.Threading.Thread.StartHelper.Callback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Thread.StartCallback()
`

**Comment by Aytackydln** [comment]
Hopefully this is fixed now. Please open new issue if it still persists
