### ISSUE TITLE
Logitech (RGB.NET) only shows one Color

### ISSUE THREAD

**Issue by HrKnuddel** [Aurora-RGB/Aurora#194]
### Expected Behaviour
The Ambilight Layer Type shows the Display i selected and the Logitech G910 Displays it correctly 

### Actual Behaviour
My Logitech G910 only show one color (in my case Green) even though the Info from the Software and the Bitmap Debug Window shows the right color (See Screenshot)
![grafik](https://github.com/Aurora-RGB/Aurora/assets/72512762/f69de73a-f480-45ff-a447-49cd0e62ad07)
If the Color green is not present in the RGB Values there will be no other Color.
It like there is only the Color Green as an option and the other are always zero
If i deactivate Aurora and let GHub take control over the Lighting of my Keyboard every Color just works fine

My Guess is, that the Color is depended on the Accent Color of Windows

### Reproduction steps
If i start the "Logitech (RGB.NET)" Device (because it always fails to start, because Aurora starts so fast, that GHub can't start in Time) it was automatically there. 

### Frequency
Everytime i did it, after i upgraded from v194 to either v210 or v211, but it still happens in v212

### Aurora Version:
v212

### Previously an Issue?
in Version v194 it wasn't

### Additional Info
I updated from v194 to try to get rid of the Problem that Aurora is starting to fast and then can't launch the Logitech integration correctly. I tried to change the Startup with Windows with a delay, but somehow it does not save the settings i make. At least at the next reboot the Settings are gone. Aurora is running with Admin Perms, so that there should be no Problems with writing the settings in a file or something. 
Maybe you can add a save Button to the General Settings Tab (maybe also other Settings tabs) and can show an error if Aurora can not save the Settings

While writing this Issue i restarted the Device-manager to get the Logitech Integration back to working because i wanted to test that my Keyboard isn't the Issue. After the Device-manager was restarted i saw every entry double, with other entries between the same entry. See Screenshot
![grafik](https://github.com/Aurora-RGB/Aurora/assets/72512762/bf034443-b79a-4a96-8923-59344378c4ef)
That may be two (or more) issues in one, but i didn't want to make multiple Issues with mostly the same Data

### Logs
[2024-01-30 06.49.17.log](https://github.com/Aurora-RGB/Aurora/files/14115556/2024-01-30.06.49.17.log)
[2024-01-30 18.19.24.log](https://github.com/Aurora-RGB/Aurora/files/14115557/2024-01-30.18.19.24.log)
[2024-01-31 17.22.16.log](https://github.com/Aurora-RGB/Aurora/files/14115558/2024-01-31.17.22.16.log)
[2024-01-31 18.20.59.log](https://github.com/Aurora-RGB/Aurora/files/14115559/2024-01-31.18.20.59.log)
[Devices-2024-01-31 18.22.26.log](https://github.com/Aurora-RGB/Aurora/files/14115555/Devices-2024-01-31.18.22.26.log)

**Comment by Aytackydln** [comment]
Does the setting save problem still happen with v212?

**Comment by Aytackydln** [comment]
Does changing device layout fix the single color issue?

**Comment by Aytackydln** [comment]
My current guess is your whole device's color is set to one key's color. Can you identify that key?

**Comment by Aytackydln** [comment]
Another thing to test, how does Aurora behave if you only have one device, only mouse and only keyboard?

**Comment by HrKnuddel** [comment]
> Does the setting save problem still happen with v212?

I checked the Box with "Start with Windows" and changed the Delay
Then i quit Aurora via the System Tray and opened it up again... the Delay was still changed, but the "Start with Windows" Box was unchecked again.
so yes

> Does changing device layout fix the single color issue?

I tried multiple diffrent Keyboard Layouts and that didn't fixed it

> My current guess is your whole device's color is set to one key's color. Can you identify that key?

I don't see any Key, that should have this color.. it would explain why everything else works, but its only showing the green color. The only other thing that maybe can influence the color should be the color my Mouse gets, when i want to look at the battery of the mouse

> Another thing to test, how does Aurora behave if you only have one device, only mouse and only keyboard?

I tried it, but it seems that nothing changes.
but while testing that I restarted the "Logitech (RGB.NET)" Device in the Device Manager, because it didn't noticed the change, and in result of that i can't relaunch it. It fails with the Info "Failed to initilazie Logitech-SDK." I relaunched GHub and then it works again. But when i did it the second time to revert the changes I made, this hotfix didn'T worked

I hope that information helped you a little

**Comment by Aytackydln** [comment]
Can you try the latest pre-release?

**Comment by HrKnuddel** [comment]
I am currently not home; i can try it on Saturday again

**Comment by HrKnuddel** [comment]
I tried the lastest pre-release and it didn't change anything

**Comment by Aytackydln** [comment]
This should be resolved in latest pre-release

**Comment by HrKnuddel** [comment]
I am sorry to tell you, but it did not fixed my problem... My keyboard still shows just the green part of the Bitmap, that it should show

**Comment by HrKnuddel** [comment]
I can provide you with more logs, with an error about the Task Scheduler
[2024-03-21 18.23.56.log](https://github.com/Aurora-RGB/Aurora/files/14705584/2024-03-21.18.23.56.log)
[2024-03-21 18.25.11.log](https://github.com/Aurora-RGB/Aurora/files/14705585/2024-03-21.18.25.11.log)
[2024-03-21 18.29.29.log](https://github.com/Aurora-RGB/Aurora/files/14705586/2024-03-21.18.29.29.log)
[Devices-2024-03-21 19.24.02.log](https://github.com/Aurora-RGB/Aurora/files/14705587/Devices-2024-03-21.19.24.02.log)
[Devices-2024-03-21 19.24.30.log](https://github.com/Aurora-RGB/Aurora/files/14705588/Devices-2024-03-21.19.24.30.log)
[Devices-2024-03-21 19.24.37.log](https://github.com/Aurora-RGB/Aurora/files/14705589/Devices-2024-03-21.19.24.37.log)
[Devices-2024-03-21 19.24.39.log](https://github.com/Aurora-RGB/Aurora/files/14705590/Devices-2024-03-21.19.24.39.log)
[Devices-2024-03-21 19.25.18.log](https://github.com/Aurora-RGB/Aurora/files/14705591/Devices-2024-03-21.19.25.18.log)
[Devices-2024-03-21 19.29.36.log](https://github.com/Aurora-RGB/Aurora/files/14705592/Devices-2024-03-21.19.29.36.log)

I hope this helps you

**Comment by Aytackydln** [comment]
you can also try non rgb.net logitech if you want
