### ISSUE TITLE
Solid Fill doesn't work after reboot

### ISSUE THREAD

**Issue by dondonini** [Aurora-RGB/Aurora#49]
### Expected Behaviour

Solid fill to work after reboot

### Actual Behaviour

Solid fill does not work after reboot

![image](https://user-images.githubusercontent.com/18273458/170336632-1baf11fc-1725-4ad0-9223-93191768c5da.png)

![image](https://user-images.githubusercontent.com/18273458/170337721-0413e464-dc41-4ed9-80c3-377b9520fcf4.png)

Profile (JSON):
[dondonini default.txt](https://github.com/Aurora-RGB/Aurora/files/8773573/dondonini.default.txt)

Log:
[2022-05-25 12.07.19.log](https://github.com/Aurora-RGB/Aurora/files/8773555/2022-05-25.12.07.19.log)

### Reproduction steps

Reboot PC and let Windows load startup programs

### Frequency

All the time

### Aurora Version:

v41

### Previously an Issue?

Nope

**Comment by dondonini** [comment]
In addition, if I duplicate the layer and delete the old one, it works again

![image](https://user-images.githubusercontent.com/18273458/170340711-78deb132-dc8f-40a2-a05b-6cca56a7e77d.png)

**Comment by Cleridwen** [comment]
Can reproduce. Editing the color makes it work again as well

**Comment by Aytackydln** [comment]
Sorry about this, I've fixed in my computer locally. This bug also breaks glitch layer but I will make new release as soon as I complete other WIP things

**Comment by dondonini** [comment]
Hello, it seems that the update didn't fix my specific situation. It is still behaving the same way. Here's an updated log: [2022-05-30 00.04.24.log](https://github.com/Aurora-RGB/Aurora/files/8795384/2022-05-30.00.04.24.log)

**Comment by Aytackydln** [comment]
can you show me your layer configuration, also with override properties if you have them too

you can export your profile too

**Comment by Aytackydln** [comment]
Sorry I've mixed up Solid Color Layer and Solid Fill layer. Fixed Solid Fill layer in the last update

**Comment by dondonini** [comment]
Can confirm that this is fixed! Thanks for the updates @Aytackydln!

**Comment by Cleridwen** [comment]
indeed, it's all good! thanks as well
